import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession } from "next-auth/react";
import Router from "next/router";
import { pegawai, att_log } from "@prisma/client";

import { DateScan, Pegawaii } from "./lib/interfaces";

const Home: NextPage = (): JSX.Element => {
  const { status, data } = useSession({
    required: true,
    onUnauthenticated() {
      Router.replace("/login");
    },
  });
  const pegawaii = data?.pegawai as pegawai;
  const attendance = data?.attendances as att_log[];
  const users = data?.users as Pegawaii;
  const months = [
    "Januari",
    "Februari",
    "Maret",
    "April",
    "Mei",
    "Juni",
    "Juli",
    "Agustus",
    "September",
    "Oktober",
    "November",
    "Desember",
  ];

  if (status === "loading") {
    return (
      <div className="flex justify-center items-center h-screen">
        <div
          className="w-12 h-12 rounded-full animate-spin
                    border-8 border-solid border-blue-700 border-t-transparent shadow-md"
        ></div>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{pegawaii.pegawai_nama}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="mt-2">
          <table className="border-collapse table-auto w-full text-sm">
            <thead>
              <tr>
                <th className="th">No</th>
                <th className="th">ID</th>
                <th className="th">Nama</th>
                <th className="th">Jabatan</th>
                <th className="th">Departemen</th>
                <th className="th">Kantor</th>
                <th className="th">Tanggal</th>
                <th className="th">Scan 1</th>
                <th className="th">Scan 2</th>
              </tr>
            </thead>
            <tbody className="bg-white ">
              {users.data.map((e, i) => {
                return (
                  <tr key={i}>
                    <td className="td">{++i}</td>
                    <td className="td">{users.nip}</td>
                    <td className="td">{users.nama}</td>
                    <td className="td">{users.jabatan}</td>
                    <td className="td">{users.departemen}</td>
                    <td className="td">{users.kantor}</td>
                    <td className="td">{e.tanggal}</td>
                    {e.scan.reverse().map((e, i) => {
                      return (
                        <td key={i + e} className="td">
                          {e}
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </main>
    </div>
  );
};

export default Home;
