import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession } from "next-auth/react";
import { useEffect } from "react";
import Router from "next/router";
import { pegawai } from "@prisma/client";

const Home: NextPage = (): JSX.Element => {
  const { status, data } = useSession();
  const pegawaii = data?.pegawai as pegawai;

  useEffect(() => {
    if (status === "unauthenticated") Router.replace("/login");
  }, [status]);

  if (status === "authenticated")
    return (
      <div className={styles.container}>
        <Head>
          <title>{pegawaii.pegawai_alias}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container mx-auto">
          <div>{JSON.stringify(data.pegawai)}</div>
        </main>
      </div>
    );

  return (
    <div className="flex justify-center items-center h-screen">
      <div
        className="w-12 h-12 rounded-full animate-spin
                    border-8 border-solid border-blue-700 border-t-transparent shadow-md"
      ></div>
    </div>
  );
};

export default Home;
